keys:
  open_router_api_key: null
  database_url: null
  # Optional: For old DB connection during migration.
  old_database_url: null

paths:
  # For temporary storage during judging, e.g. for file extraction, intermediate files, etc.
  scratch_path: null

  # For excel recalculation before CSV extraction.
  libreoffice_path: null

miscs:
  logger_name: "bizbench_judge"
  log_to_terminal: true

judge:
  # The prompt template to use for judging. Should be a YAML file in the judge/prompts directory.
  prompt_template: "prompts/judge_template_6_3.yaml"

  # The rubric file containing subdimension and description
  rubric: "prompts/rubrics/rubric_7.json"
